const ALL_FONTS=[];
const ARABIC_FONTS=[];
const ANDALUSI_FONTS=[];
const $=id=>document.getElementById(id);
const input=$("input"),fontName=$("fontName"),fontSource=$("fontSource"),fontIndex=$("fontIndex"),bigFontName=$("bigFontName"),count=$("count"),countLabel=$("countLabel"),sizeValue=$("sizeValue"),fontCard=$("fontCard"),currentFontLink=$("currentFontLink"),directoryCount=$("directoryCount"),fontDirectoryList=$("fontDirectoryList"),fontDirectoryTitle=$("fontDirectoryTitle"),contextHeadline=$("contextHeadline"),contextNote=$("contextNote"),searchHeadTitle=$("searchHeadTitle"),andalusiDirectory=$("andalusiDirectory"),andalusiCount=$("andalusiCount"),andalusiSearch=$("andalusiSearch"),andalusiCategory=$("andalusiCategory"),andalusiList=$("andalusiList");
let currentIndex=0,fontSize=52,fontWeight=700,changingTimer=null,currentContext=new URLSearchParams(location.search).get("context")==="ar"?"ar":"fa",directoryCleanup=()=>{};
const contextText={fa:"سلام دنیا",ar:"مرحباً بالعالم"};
const andalusiCategoryLabels={"New Fonts":"خطوط جديدة",Naskh:"نسخ","Modern Naskh":"نسخ حديث",Kufi:"كوفي","Modern Kufi":"كوفي حديث","Free Hand":"خط حر",Ruqaa:"رقعة",Thuluth:"ثلث",Diwani:"ديواني",Nastaliq:"نستعليق",Exclusive:"حصرية",Serif:"سريف","Sans Serif":"سانس سريف",Monospaced:"أحادي المسافة",Script:"كتابي",Display:"عرض",Handwritten:"يدوي"};
const activeFonts=()=>currentContext==="ar"?ARABIC_FONTS:ALL_FONTS;
const contextQuery=()=>currentContext==="ar"?"&context=ar":"";
const requested=new Set();
function loadWebFonts(){for(const f of CDN_FONTS){const l=document.createElement("link");l.rel="stylesheet";l.href=f.url;document.head.appendChild(l)}for(let i=0;i<GOOGLE_FONTS.length;i+=10){const families=GOOGLE_FONTS.slice(i,i+10).map(n=>`family=${encodeURIComponent(n).replace(/%20/g,"+")}`).join("&");const l=document.createElement("link");l.rel="stylesheet";l.href=`https://fonts.googleapis.com/css2?${families}&display=swap`;document.head.appendChild(l)}}
function loadLocalFont(font){if(!font.web||requested.has(font.family))return;requested.add(font.family);new FontFace(font.family,`url("fonts-woff2/${encodeURIComponent(font.web)}") format("woff2")`).load().then(face=>document.fonts.add(face)).catch(()=>{})}
function animateFontChange(){fontCard.classList.add("changing");clearTimeout(changingTimer);changingTimer=setTimeout(()=>fontCard.classList.remove("changing"),170)}
function showFont(index,animate=true){const fonts=activeFonts();if(!fonts.length)return;currentIndex=(index+fonts.length)%fonts.length;const f=fonts[currentIndex];if(animate)animateFontChange();fontName.textContent=f.name;bigFontName.textContent=f.name;fontSource.textContent=f.source||"LOCAL";fontIndex.textContent=`${String(currentIndex+1).padStart(2,"0")} / ${String(fonts.length).padStart(2,"0")}`;input.style.fontFamily=`"${f.family}",sans-serif`;input.style.fontSize=`${fontSize}px`;input.style.fontWeight=fontWeight;sizeValue.textContent=fontSize;if(f.file&&f.web)loadLocalFont(f);currentFontLink.href=`font?f=${encodeURIComponent(f.family)}&lang=fa${contextQuery()}`}
function next(){showFont(currentIndex+1)}function prev(){showFont(currentIndex-1)}
$("nextFont").onclick=next;$("prevFont").onclick=prev;
$("randomBtn").onclick=()=>showFont(Math.floor(Math.random()*activeFonts().length));
$("sizeUp").onclick=()=>{fontSize=Math.min(120,fontSize+4);showFont(currentIndex,false)};
$("sizeDown").onclick=()=>{fontSize=Math.max(16,fontSize-4);showFont(currentIndex,false)};
document.querySelectorAll("[data-weight]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-weight]").forEach(x=>x.classList.remove("active"));b.classList.add("active");fontWeight=Number(b.dataset.weight);showFont(currentIndex,false)});
$("centerBtn").onclick=()=>{input.style.textAlign=input.style.textAlign==="center"?"right":"center"};
input.addEventListener("input",()=>{contextText[currentContext]=input.value;input.style.transform="scale(1.003)";setTimeout(()=>input.style.transform="",90)});
document.addEventListener("keydown",e=>{if(e.target.matches("textarea,input"))return;if(e.key==="ArrowRight")next();if(e.key==="ArrowLeft")prev();if(e.key===" "){e.preventDefault();showFont(Math.floor(Math.random()*activeFonts().length))}if(e.key==="Enter")showToast("فونت انتخاب شد · "+(activeFonts()[currentIndex]?.name||""));if(e.key==="/"){e.preventDefault();openSearch()}});
const overlay=$("searchOverlay"),filter=$("filter"),results=$("searchResults");
function openSearch(){overlay.classList.add("open");filter.focus();renderSearch()}function closeSearch(){overlay.classList.remove("open");filter.value=""}$("searchBtn").onclick=openSearch;$("closeSearch").onclick=closeSearch;overlay.onclick=e=>{if(e.target===overlay)closeSearch()};filter.oninput=renderSearch;
function renderSearch(){const q=filter.value.trim().toLowerCase();const list=activeFonts().map((font,index)=>({font,index})).filter(x=>!q||x.font.name.toLowerCase().includes(q)).slice(0,18);results.innerHTML=list.map(({font,index})=>`<div class="search-result" data-index="${index}"><span>${escapeHtml(font.name)}</span><small>${escapeHtml(font.source||"")}</small><a class="search-result-info" href="font?f=${encodeURIComponent(font.family)}${contextQuery()}" target="_blank" rel="noopener" title="درباره این فونت" onclick="event.stopPropagation()">ⓘ</a></div>`).join("");results.querySelectorAll(".search-result").forEach(el=>el.onclick=()=>{showFont(Number(el.dataset.index));closeSearch()})}
$("downloadBtn").onclick=()=>{const f=activeFonts()[currentIndex];if(!f)return;if(f.file&&f.open){const a=document.createElement("a");a.href=`fonts/${encodeURIComponent(f.file)}`;a.download=f.file;a.click();showToast("دانلود شروع شد · "+f.name)}else{window.open(f.link||f.sourceUrl,"_blank","noopener,noreferrer");showToast("منبع فونت باز شد")}};
function escapeHtml(s){const d=document.createElement("div");d.textContent=s;return d.innerHTML}
function activateDirectoryFont(entry,font){const sample=entry.querySelector(".font-directory-sample");sample.style.fontFamily=`"${font.family}",sans-serif`;if(font.source==="LOCAL")loadLocalFont(font)}
function renderFontDirectory(){directoryCleanup();const context=currentContext,fonts=activeFonts(),unique=[...new Map(fonts.map(font=>[font.family,font])).values()].sort((a,b)=>a.name.localeCompare(b.name,context,{sensitivity:"base"})),sample=contextText[context],language=context==="ar"?"ar":"fa";fontDirectoryTitle.textContent=context==="ar"?"كل الخطوط العربية":"همهٔ فونت‌های فارسی";directoryCount.textContent=context==="ar"?`${unique.length.toLocaleString("ar-EG")} خط عربي`:`${unique.length.toLocaleString("fa-IR")} فونت`;fontDirectoryList.innerHTML=unique.map((font,index)=>`<a href="font?f=${encodeURIComponent(font.family)}&lang=fa${contextQuery()}" data-directory-index="${index}"><span>${escapeHtml(font.name)}</span><small class="font-directory-sample" lang="${language}" dir="rtl">${escapeHtml(sample)}</small></a>`).join("");const pending=new Set(fontDirectoryList.querySelectorAll("[data-directory-index]"));let frame=null;const activateNearby=()=>{frame=null;for(const entry of pending){const rect=entry.getBoundingClientRect();if(rect.top>innerHeight+500||rect.bottom< -500)continue;activateDirectoryFont(entry,unique[Number(entry.dataset.directoryIndex)]);pending.delete(entry)}if(!pending.size)cleanup()};const schedule=()=>{if(frame===null)frame=requestAnimationFrame(activateNearby)};const cleanup=()=>{removeEventListener("scroll",schedule);removeEventListener("resize",schedule);if(frame!==null)cancelAnimationFrame(frame)};directoryCleanup=cleanup;addEventListener("scroll",schedule,{passive:true});addEventListener("resize",schedule);schedule()}
function renderAndalusiDirectory(){const visible=currentContext==="ar";andalusiDirectory.hidden=!visible;if(!visible)return;const query=andalusiSearch.value.trim().toLocaleLowerCase("ar"),category=andalusiCategory.value,fonts=ANDALUSI_FONTS.filter(font=>(!category||font.category===category)&&(!query||`${font.name} ${font.arabicName}`.toLocaleLowerCase("ar").includes(query)));andalusiCount.textContent=`${fonts.length.toLocaleString("ar-EG")} خطاً`;andalusiList.innerHTML=fonts.map(font=>`<a href="${font.url}" target="_blank" rel="noopener noreferrer"><span><b>${escapeHtml(font.name)}</b><small lang="ar" dir="rtl">${escapeHtml(font.arabicName)}</small></span><em>${escapeHtml(andalusiCategoryLabels[font.category]||font.category)}</em><i aria-hidden="true">↗</i></a>`).join("")}
function applyContextUi(){const arabic=currentContext==="ar";document.documentElement.lang=arabic?"ar":"fa";document.title=arabic?"قلم‌نما | استعراض الخطوط العربية":"قلم‌نما | پیش‌نمایش و دانلود فونت فارسی";contextHeadline.innerHTML=arabic?'اكتشف جمال <em>الخط العربي.</em>':'فونت فارسی رو <em>حس کن.</em>';contextNote.innerHTML=arabic?'اكتب نصّك، وتنقّل باستخدام ← →<br>واعثر على الخط الأنسب.':'متنت رو بنویس، با ← → بچرخ<br>و فونتی که بهش میاد رو پیدا کن.';countLabel.textContent=arabic?"خط عربي":"فونت آنلاین";searchHeadTitle.textContent=arabic?"ابحث عن خط":"Find a typeface";filter.placeholder=arabic?"اكتب اسم الخط…":"نام فونت را بنویس…"}
function setContext(context){if(context===currentContext)return;contextText[currentContext]=input.value;currentContext=context;currentIndex=0;input.value=contextText[context];input.lang=context==="ar"?"ar":"fa";const url=new URL(location.href);if(context==="ar")url.searchParams.set("context","ar");else url.searchParams.delete("context");history.replaceState(null,"",url);document.querySelectorAll("[data-context]").forEach(button=>button.setAttribute("aria-pressed",String(button.dataset.context===context)));applyContextUi();count.textContent=activeFonts().length;showFont(0);renderFontDirectory();renderAndalusiDirectory();if(overlay.classList.contains("open"))renderSearch()}
let toastTimer;function showToast(t){const el=$("toast");el.textContent=t;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),1800)}
async function init(){loadWebFonts();let pack=[],arabic=[],andalusi=[];try{const [packResponse,arabicResponse,andalusiResponse]=await Promise.all([fetch("fonts.json"),fetch("arabic-fonts.json"),fetch("andalusi-fonts.json")]);if(packResponse.ok)pack=await packResponse.json();if(arabicResponse.ok)arabic=await arabicResponse.json();if(andalusiResponse.ok)andalusi=await andalusiResponse.json()}catch{}const persian=[...pack.map(f=>({...f,source:"LOCAL"})),...CDN_FONTS.map(f=>WEB_FONTS.find(web=>web.family===f.name))];ALL_FONTS.push(...new Map(persian.map(font=>[font.family,font])).values());ARABIC_FONTS.push(...arabic.map(f=>({...f,link:f.sourceUrl})));ANDALUSI_FONTS.push(...andalusi);for(const category of [...new Set(andalusi.map(font=>font.category))]){const option=document.createElement("option");option.value=category;option.textContent=andalusiCategoryLabels[category]||category;andalusiCategory.appendChild(option)}andalusiSearch.oninput=renderAndalusiDirectory;andalusiCategory.onchange=renderAndalusiDirectory;document.querySelectorAll("[data-context]").forEach(button=>{button.setAttribute("aria-pressed",String(button.dataset.context===currentContext));button.onclick=()=>setContext(button.dataset.context)});input.value=contextText[currentContext];input.lang=currentContext==="ar"?"ar":"fa";applyContextUi();count.textContent=activeFonts().length;showFont(0,false);renderFontDirectory();renderAndalusiDirectory()}init();
